name: correspondence_spair
random_seed: 8
split: test
image_size: 800
eval_class: all
num_instances: null
data_root: ${oc.env:SPAIR_ROOT,data/SPair-71k}
use_bbox: false
multilayer: false
soft_eval: false
soft_eval_beta: 0.02
soft_eval_window: 7
note: ""
runner:
  module: omniprobe.scripts.eval_correspondence_spair
  required_output: dense
