name: correspondence_ap10k
random_seed: 8
split: test
data_root: ${oc.env:AP10K_ROOT,data/AP-10K}
image_size: 800
eval_class: all
num_instances: 5000
use_bbox: false
multilayer: false
note: ""
thresh: 0.10
eval_subset: intra-species
runner:
  module: omniprobe.scripts.eval_correspondence_ap10k
  required_output: dense
