defaults:
  - /dataset: tapvid
  - _self_

name: tracking_tapvid
random_seed: 8
multilayer: false
feature:
  input_size: [448, 448]
  frame_chunk: 32
dataloader_workers: 2
runner:
  module: omniprobe.scripts.eval_tracking_tapvid
  required_output: dense
