random_seed: 8
data_root: ${oc.env:SOCO_ROOT,data/SOCOv1}
pair_subdir: PairAnnotations/intra
image_size: 800
num_patches: 60
fixed_patched_size: false
image_mean: ${oc.select:backbone.image_mean,imagenet}
use_bbox: false
classes: all  # or list of class names
max_pairs: null
thresh: 0.10
mask_feats: false
multilayer: false
num_visualize: 0
soft_eval: false
soft_eval_beta: 0.02
soft_eval_window: 7
reduction: pair      # Options: keypoint (pool all, then threshold), pair (threshold per pair, then average)

defaults:
  - backbone: dinov2_b14
  - _self_

task_name: correspondence_soco

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${task_name}_${hydra:runtime.choices.backbone}
