random_seed: 8
split: test
image_size: 840 # I better have this consistent with spair etc (800)
eval_class: all
num_instances: 5000
image_mean: ${oc.select:backbone.image_mean,imagenet}
use_bbox: False
multilayer: False
note: ""

# AP-10K specific settings
data_root: ${oc.env:AP10K_ROOT,data/AP-10K}
thresh: 0.10
# eval_subset options: 'intra-species', 'cross-species', 'cross-family'
eval_subset: 'intra-species'

defaults:
  - backbone: dinov2_b14
  - _self_

task_name: correspondence_ap10k

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${task_name}_${hydra:runtime.choices.backbone}
