defaults:
  - backbone: dinov2_b14
  - dataset: tapvid
  - _self_

random_seed: 8
image_mean: ${oc.select:backbone.image_mean,imagenet}
multilayer: false

feature:
  input_size: [448, 448]
  frame_chunk: 32

dataloader_workers: 2

task_name: tracking_tapvid

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${task_name}_${hydra:runtime.choices.backbone}
