random_seed: 8
scale_factor: 0.25
num_corr: 1000
multilayer: False
image_mean: ${oc.select:backbone.image_mean,perception}
defaults:
  - backbone: dinov2_b14
  - _self_

task_name: correspondence_scannet

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${task_name}_${hydra:runtime.choices.backbone}
