system:
  random_seed: 8
  num_gpus: 1
  port: 12355
  max_steps_per_epoch: 0
  max_eval_batches: 0
note: ""
batch_size: 8
defaults:
  - optimizer: ten_epoch
  - backbone: dinov2_b14
  - dataset: nyu
  - probe: depth_dpt
  - _self_

task_name: depth

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${task_name}_${hydra:runtime.choices.backbone}
